### ISSUE TITLE
Resolve unknown fype will show "Command 'maven.artifactSearch'" fails.

### ISSUE THREAD

**Issue by Elvira-sxr** [microsoft/vscode-maven#474]
**Describe the bug**
Resolve unknown fype will show "Command 'maven.artifactSearch'" fails.

**To Reproduce**
1. Open a Maven project in VS Code, and open a .java file. In body of a function, type below statements.
```
Gson gson;
StringUtils.capitalize("abc");
```
2.  Open Code Actions, "Resolve unknown type" is in the list.
3. Clicking "Resolve unknown type", it will show error message.

![image](https://user-images.githubusercontent.com/51812626/75973766-b0e2f200-5f10-11ea-94f0-e8012afb8950.png)

**Environments:**
 - OS: Win10
 - VS Code version: 1.42.1
 - VSCode language server version : 0.58.0
 - Maven for java version : 0.21.0

**Comment by Eskibear** [comment]
I can reproduce it **iff.** I'm using Java 13

**Comment by Eskibear** [comment]
```
[Error - 11:46:43 AM] Mar 6, 2020, 11:46:43 AM Error in calling delegate command handler
org/codehaus/plexus/configuration/PlexusConfiguration
java.lang.NoClassDefFoundError: org/codehaus/plexus/configuration/PlexusConfiguration
	at org.apache.maven.index.ArtifactInfo.<clinit>(ArtifactInfo.java:138)
	at org.apache.maven.index.FlatSearchRequest.<init>(FlatSearchRequest.java:50)
	at com.microsoft.java.maven.BaseClassSearcher.search(ArtifactSearcher.java:381)
	at com.microsoft.java.maven.BaseClassSearcher.searchByClassName(ArtifactSearcher.java:339)
	at com.microsoft.java.maven.ClassSearcher.searchByClassName(ArtifactSearcher.java:213)
	at com.microsoft.java.maven.ArtifactSearcher.searchByClassName(ArtifactSearcher.java:80)
	at com.microsoft.java.maven.handler.DelegateCommandHandler.executeCommand(DelegateCommandHandler.java:35)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:215)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:205)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:480)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$48(JDTLanguageServer.java:972)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.ClassNotFoundException: org.codehaus.plexus.configuration.PlexusConfiguration cannot be found by com.microsoft.java.maven.plugin_0.21.0
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:516)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 19 more
```

**Comment by Eskibear** [comment]
@Elvira-sxr Could you verify the latest CI build for the fix?

**Comment by Elvira-sxr** [comment]
test pass
