### ISSUE TITLE
Unable to debug after adding library to pom.xml file

### ISSUE THREAD

**Issue by pughua** [microsoft/vscode-maven#645]
**Describe the bug**
Unable to debug after adding library to pom.xml file.Program Error: Could not find or load main class.

**To Reproduce**
1. Create a new “maven-archetype-quickstart” project using "com.example",“demo”.
2. Add a breakpoint in "app.java" and run it by pressing F5.It's working and it's at the breakpoint.
3. Open "pom.xml" and add dependency package "org.reflections".And update the project.
4. Add a breakpoint in "app.java" and run it by pressing F5.Program Error: Could not find or load main class.
5. Open "pom.xml" and remove dependency package "org.reflections".And update the project.
6. Add a breakpoint in "app.java" and run it by pressing F5.It's working and it's at the breakpoint.

**Expected behavior**
Hopefully it will work when you add a dependency package

**Environments:**
 - OS: Windows 10
 - VS Code version: 1.57.0
 - Extension version: Maven for Java v0.31.0
 - Debugger for Java: v0.34.0

**Run the information**

`
1.Before adding a dependency package
PS D:\文档\Git\JavaProject\demo>  d:; cd 'd:\ĵ\Git\JavaProject\demo'; & 'c:\Users\lemonnc\.vscode\extensions\vscjava.vscode-java-debug-0.34.0\scripts\launcher.bat' 'D:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-hotspot\bin\java.exe' '-agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:53351' '-Dfile.encoding=UTF-8' '-cp' 'D:\ĵ\Git\JavaProject\demo\target\classes' 'com.example.App' 
Hello World!
2.After adding a dependency package
PS D:\文档\Git\JavaProject\demo>  d:; cd 'd:\ĵ\Git\JavaProject\demo'; & 'c:\Users\lemonnc\.vscode\extensions\vscjava.vscode-java-debug-0.34.0\scripts\launcher.bat' 'D:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-hotspot\bin\java.exe' '-agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:53377' '-Dfile.encoding=UTF-8' '@C:\Users\xxxx\AppData\Local\Temp\cp_elrq980gdoztxi0tmpyepn1ao.argfile' 'com.example.App' 
错误: 找不到或无法加载主类 com.example.App
原因: java.lang.ClassNotFoundException: com.example.App
3.After removing the dependent packages
PS D:\文档\Git\JavaProject\demo>  d:; cd 'd:\ĵ\Git\JavaProject\demo'; & 'c:\Users\lemonnc\.vscode\extensions\vscjava.vscode-java-debug-0.34.0\scripts\launcher.bat' 'D:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-hotspot\bin\java.exe' '-agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:63844' '-Dfile.encoding=UTF-8' '-cp' 'D:\ĵ\Git\JavaProject\demo\target\classes' 'com.example.App' 
Hello World!
`

**Additional context**
For some reason, the running directory changed after the dependency package was added.

as "C:\Users\XXXXX\AppData\Local\Temp\cp_elrq980gdoztxi0tmpyepn1ao.argfile"

**Comment by Eskibear** [comment]
After performing Step 4, I cannot reproduce the issue. No error and the breakpoint was hit.

![image](https://user-images.githubusercontent.com/2351748/122162249-d269b200-cea5-11eb-96a8-8259ea259e4b.png)


@testforstephen Any thoughts?

**Comment by testforstephen** [comment]
Please try "Ctrl + F5" to run the application, and share the tmp file "C:\Users\XXXXX\AppData\Local\Temp\cp_elrq980gdoztxi0tmpyepn1ao.argfile".

**Comment by pughua** [comment]
I don't know what more information to provide, and I've re-created the project several times to the issue.
@Eskibear 
![image](https://user-images.githubusercontent.com/780726/122164213-0692a200-cea9-11eb-9de8-b78ac6f3e481.png)

![image](https://user-images.githubusercontent.com/780726/122164521-80c32680-cea9-11eb-857e-f102ad900957.png)

![image](https://user-images.githubusercontent.com/780726/122164580-989aaa80-cea9-11eb-8037-d296de296992.png)

**Comment by testforstephen** [comment]
I suspect this is because of the Chinese directory "D:\文档".  `D:\文档 -> d:\ĵ` looks like some unicode chars in your path.

Could you move your demo to an English directory and try again?

**Comment by pughua** [comment]
1.I have the same error when I move the project to another directory

`
PS D:\code\JavaProject\demo>  d:; cd 'd:\code\JavaProject\demo'; & 'c:\Users\lemonnc\.vscode\extensions\vscjava.vscode-java-debug-0.34.0\scripts\launcher.bat' 'D:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-hotspot\bin\java.exe' '-agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:62002' '-Dfile.encoding=UTF-8' '@C:\Users\lemonnc\AppData\Local\Temp\cp_efrici4hkvvmbzbtua1o5gwjc.argfile' 'com.example.App' 
原因: java.lang.ClassNotFoundException: com.example.App
`

2.I can debug it by adding the following to "launch.json",and update project.

`
"classPaths": [
                "${workspaceRoot}/target/classes"
            ]
`

`

PS D:\code\JavaProject\demo>  d:; cd 'd:\code\JavaProject\demo'; & 'c:\Users\lemonnc\.vscode\extensions\vscjava.vscode-java-debug-0.34.0\scripts\launcher.bat' 'D:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-hotspot\bin\java.exe' '-agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:55763' '-Dfile.encoding=UTF-8' '-cp' 
'd:\code\JavaProject\demo\target\classes' 'com.example.App' 
Hello World!
`

3.The following error occurs when I add the following code to "app.java"

![image](https://user-images.githubusercontent.com/780726/122171230-12cf2d00-ceb2-11eb-8dba-f1698c6b265d.png)


`
PS D:\code\JavaProject\demo>  d:; cd 'd:\code\JavaProject\demo'; & 'c:\Users\lemonnc\.vscode\extensions\vscjava.vscode-java-debug-0.34.0\scripts\launcher.bat' 'D:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-hotspot\bin\java.exe' '-agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:55294' '-Dfile.encoding=UTF-8' '-cp' 
'd:\code\JavaProject\demo\target\classes' 'com.example.App'
Exception in thread "main" java.lang.NoClassDefFoundError: org/reflections/util/ConfigurationBuilder
        at com.example.App.main(App.java:13)
Caused by: java.lang.ClassNotFoundException: org.reflections.util.ConfigurationBuilder
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 1 more
`
