### ISSUE TITLE
Current working directory is wrong when pom.xml is in subdirectory of root

### ISSUE THREAD

**Issue by joshunger** [Microsoft/vscode-maven#78]
**Describe the bug**
The current working directory is wrong when pom.xml is in subdirectory of root. This causes path issues when executing a `spring-boot:run` command. Can you `cd` over to the directory of the `pom.xml` as default behavior?

As a comparison, when you execute a maven goal in Intellij it defaults the working directory to the same directory as the `pom.xml` file.

**Comment by Eskibear** [comment]
I just created a simple spring-boot project with spring initializr in subdirectory of root. And `spring-boot:run -f <pom file path>` just works for me. I cannot reproduce any "path issues". Can you provide more details?

Back to the `cd` suggestion, some users may think it's useful while some others would rather stay at root folder. We prefer not to interfere too much if it is not blocking.

**Comment by joshunger** [comment]
Yes, it is blocking me. Unfortunately, it is private code so I can't upload it bu here is the stack trace.

```
2018-07-13_06:40:29.424 [http-nio-8080-exec-5] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - [DirectJDKLog.java:181] [] [] - Servlet.service() for servlet [dispatcherServlet] in context with path [/xxxx] threw exception [Could not resolve view with name 'xxxx-view' in servlet with name 'dispatcherServlet'] with root cause
javax.servlet.ServletException: Could not resolve view with name 'xxxx-view' in servlet with name 'dispatcherServlet'
        at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1262)
        at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1037)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:980)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
```

**Comment by Eskibear** [comment]
> Why did you pick not cd'ing over to the current directory as the original design?

I was working on a project with many modules in subdirectories. When I was going to only `clean install` one module, I wanted the terminal's cwd to remain the root directory instead of `cd` into the subdirectory, so I could conveniently continue execute some commands in it. 

From mvn's manual, `mvn <goal> -f path/to/pom.xml` should have the same behavior with `cd path/to && mvn <goal>` (correct me if I'm wrong). But since it blocks you, I'll re-consider the design. Thanks for your information.

**Comment by adrianmoya** [comment]
>  I wanted the terminal's cwd to remain the root directory instead of cd into the subdirectory, so I could conveniently continue execute some commands in it.

This is because the design was to use a terminal, but read my comment on #68, if this plugin used an output window, you could have your terminal open for commands and execute different maven goals without interfering with your terminal. I think it would be a better design.

**Comment by Eskibear** [comment]
We’ve considered using output at very beginning, but Terminal is more flexible and transparent, so we finally use terminal. In fact it doesn’t matter because we can have multiple terminals open in vscode

**Comment by Eskibear** [comment]
One more point is, commonly we have maven wrapper in the root folder, and `./mvnw` will not be found if we cd into sub-directories.
