### ISSUE TITLE
LDAP user failed to activate the ext

### ISSUE THREAD

**Issue by haotianzh** [microsoft/vscode-maven#996]
Type: <b>Bug</b>

I am a LDAP user. There should be a bug in activaton of the ext, below is the output from logs.
--------------------------------------------------------------------------------------------------
2023-09-19 19:15:41.911 [error] SystemError: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
	at new SystemError (node:internal/errors:250:5)
	at new NodeError (node:internal/errors:361:7)
	at Object.userInfo (node:os:357:11)
	at /home/haz19024/.vscode/extensions/vscjava.vscode-maven-0.42.0/dist/extension.js:2:954348
	at Generator.next (<anonymous>)
	at s (/home/haz19024/.vscode/extensions/vscjava.vscode-maven-0.42.0/dist/extension.js:2:953136)

Extension version: 0.42.0
VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:51:20.981Z)
OS version: Linux x64 6.2.0-32-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen Threadripper PRO 5955WX 16-Cores (32 x 3127)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 0|
|Memory (System)|251.49GB (242.22GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id a97c1cc4-01a7-4216-9a13-a7a0ebff974c|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
a2ce3375:30757347
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
copilotsettingt:30839829
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571
dsvsc015cf:30829746

```

</details>

**Comment by testforstephen** [comment]
This error is related to `os.userInfo()`, we need to find a way to avoid using it.

https://github.com/microsoft/vscode-maven/blob/fe5230ad30124b3d1f9161ad1fd901dad8d91131/src/utils/contextUtils.ts#L31

**Comment by afaucon** [comment]
Hello @testforstephen, what position has this bug in your backlog?
